services:
  postgres:
    shm_size: 1g
    security_opt:
      - no-new-privileges:true
      - apparmor:docker-default
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - FOWNER
    tmpfs:
      - /tmp:noexec,nosuid,size=100m,uid=999,gid=999
      - /var/run/postgresql:noexec,nosuid,size=10m,uid=999,gid=999
