name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ci-${{ github.sha }}
      IMAGE_REFERENCE: ghcr.io/kayjay-madman/postgres-combo:ci-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y jq bc
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Build image
        run: make build

      - name: Run integration tests
        run: make test

      - name: Run security scan
        run: make scan
