name: Test Docker Build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: gha-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare environment file
      run: |
        cat <<EOT > .env
POSTGRES_PASSWORD=test_password_123
POSTGRES_USER=postgres
POSTGRES_DB=postgres
POSTGRES_HOST_PORT=5433
CONTAINER_NAME=postgres-combo
IMAGE_NAME=ghcr.io/kayjay-madman/postgres-combo
IMAGE_TAG=${IMAGE_TAG}
EOT

    - name: Build Docker image
      run: |
        make build IMAGE_TAG=${IMAGE_TAG} BUILD_CMD="docker buildx build --load"

    - name: Run integration tests
      run: |
        make test IMAGE_TAG=${IMAGE_TAG}

    - name: Show logs on failure
      if: failure()
      run: |
        docker compose -f docker-compose.yml -f docker-compose.hardened.yml logs postgres || true

    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.yml -f docker-compose.hardened.yml down -v || true
